-- =============================================================================
-- VERDICT — placeholder scenario seed
-- 200 scenarios across 12 categories. Source = 'curated'. Placeholders.
-- All real names anonymized. Side labels + meanings are scenario-specific.
-- Replace via scripts/import-scenarios.ts before public launch.
-- =============================================================================

begin;

insert into public.scenarios
  (text, question, context_tag, side_a_label, side_b_label, side_a_meaning, side_b_meaning, category, freshness_tier, source) values
-- -----------------------------------------------------------------------------
-- personal_relationships (17)
-- -----------------------------------------------------------------------------
(e'A woman discovers her brother has been quietly paying her rent for two years without telling her. She had believed the studio was rent-controlled. When she finds out, she stops accepting his money, repays what she can, and moves to a smaller flat she can afford on her own. Her brother is hurt — he says she has taken away something he wanted to give.', e'Was she right to refuse the help?', 'Family · Pride', 'Right to refuse', 'Wrong to refuse', 'Adult independence is not a debt to anyone.', 'Help offered in love does not become an insult.', 'personal_relationships', 'evergreen', 'curated'),
(e'A man finds his wife’s old diary while clearing out a cupboard. He reads it cover to cover. It contains nothing she has hidden from him — only feelings she once had, and never spoke aloud. He tells her about it weeks later, in an argument.', e'Was reading it justified?', 'Marriage · Trust', 'Justified', 'Not justified', 'Curiosity in a shared home is not a betrayal.', 'Privacy is the floor a marriage stands on.', 'personal_relationships', 'evergreen', 'curated'),
(e'A daughter cuts off contact with her father after he refuses to apologize for something he said at her wedding. Two years pass. He is diagnosed with a condition that may shorten his life. She does not return his calls. She believes he is using the diagnosis to manipulate her.', e'Was she right to stay away?', 'Estrangement', 'Right to stay away', 'Wrong to stay away', 'A boundary is not a punishment to be lifted on schedule.', 'There are some doors you do not get a second chance to walk through.', 'personal_relationships', 'evergreen', 'curated'),
(e'A bride asks her best friend, who is recovering from an eating disorder, not to attend the bachelorette weekend because of how the trip might affect her. The friend is grateful at first, then later furious. She says she felt erased.', e'Was the bride right to ask?', 'Friendship · Care', 'Right to ask', 'Wrong to ask', 'Protecting someone is sometimes the kindest exclusion.', 'Care that decides for someone is not care.', 'personal_relationships', 'evergreen', 'curated'),
(e'A man finds out his cousin has been telling people in their extended family that he is in financial trouble — which is a lie. The cousin says she was trying to deflect attention from her own divorce. He confronts her publicly at a family dinner.', e'Was the public confrontation justified?', 'Family · Honesty', 'Justified', 'Not justified', 'A lie made public deserves to be corrected in public.', 'A family table is not the right courtroom.', 'personal_relationships', 'evergreen', 'curated'),
(e'A woman ends a six-year friendship over a single political argument that has nothing to do with their daily lives. She says the friendship had been hollow for years; the argument simply confirmed it.', e'Was ending it justified?', 'Friendship · Drift', 'Justified', 'Not justified', 'A long friendship can be honestly outgrown.', 'Six years deserved a conversation, not an exit.', 'personal_relationships', 'evergreen', 'curated'),
(e'A father refuses to walk his daughter down the aisle because she is marrying someone he does not approve of. He does attend the wedding. He sits in the front row and weeps.', e'Was he right to refuse the walk?', 'Family · Ritual', 'Right to refuse', 'Wrong to refuse', 'A blessing cannot be performed if it is not felt.', 'A wedding day is not the day for a private protest.', 'personal_relationships', 'evergreen', 'curated'),
(e'A woman’s mother-in-law moves in for what was supposed to be a month of recovery after surgery. Eight months later she is still there, and the woman is exhausted. She asks her husband to set a deadline. He refuses. She tells her mother-in-law herself.', e'Was she justified in telling her directly?', 'In-laws · Boundaries', 'Justified', 'Not justified', 'Her home is also her home.', 'It should have gone through her husband.', 'personal_relationships', 'evergreen', 'curated'),
(e'A man tells his pregnant partner he does not want to be present at the birth because he is afraid he will faint and embarrass her. He offers to be in the next room. She is hurt and goes through it alone.', e'Was he right to step back?', 'Parenting · Fear', 'Right to step back', 'Wrong to step back', 'Honest fear is better than a forced presence.', 'A birth is not a place to manage your image.', 'personal_relationships', 'evergreen', 'curated'),
(e'A woman secretly takes a DNA test that confirms her uncle is, in fact, her biological father. She tells no one. She lets her mother and her uncle live out their lives in the family they built around the lie.', e'Was she right to stay silent?', 'Family · Secrets', 'Right to stay silent', 'Wrong to stay silent', 'A truth without a use case can be a cruelty.', 'Everyone in that house had a right to know.', 'personal_relationships', 'topical', 'curated'),
(e'A man discovers that his teenage son has been bullying a classmate online for months. He makes his son write a public apology, hand-deliver it to the classmate’s parents, and quit the football team his son loves.', e'Was the punishment proportionate?', 'Parenting · Discipline', 'Proportionate', 'Excessive', 'Cruelty learned young is hardest to unlearn later.', 'A teenager broken in public learns shame, not change.', 'personal_relationships', 'evergreen', 'curated'),
(e'A woman in her forties refuses to attend her sister’s wedding because the sister has invited their estranged father. The bride says the day is not about the sister; the sister says the invitation is.', e'Was she right to skip it?', 'Family · Loyalty', 'Right to skip', 'Wrong to skip', 'You do not have to share a room with someone you’ve survived.', 'A sister’s day is not the right day to draw the line.', 'personal_relationships', 'evergreen', 'curated'),
(e'A man pays for his sister’s wedding entirely out of pocket — about eight months of his salary — and never mentions the cost. She finds out from a cousin a year later, and confronts him for not letting her contribute.', e'Was he right to hide it?', 'Family · Generosity', 'Right to hide it', 'Wrong to hide it', 'A gift declared is a gift weighed.', 'Adults deserve to know what they are accepting.', 'personal_relationships', 'evergreen', 'curated'),
(e'A woman tells her best friend that her fiancé made a pass at her at a party. The friend confronts the fiancé, who denies it. The wedding is called off. Months later, the friend admits she may have misread the moment.', e'Was she right to tell her?', 'Friendship · Loyalty', 'Right to tell', 'Wrong to tell', 'Silence about something like that is its own kind of betrayal.', 'A single ambiguous moment is not worth a marriage.', 'personal_relationships', 'evergreen', 'curated'),
(e'A grandmother refuses to babysit her grandchild during the week, saying she raised her own children and is now retired. Her daughter, a single mother, is forced to leave a job she loves for one with daycare hours.', e'Was the grandmother justified?', 'Family · Generations', 'Justified', 'Not justified', 'Retirement is a stage no one else gets to schedule.', 'Family is the obligation you do not get to retire from.', 'personal_relationships', 'evergreen', 'curated'),
(e'A man asks his partner of nine years to sign a postnuptial agreement before they buy a house together. She agrees but says something between them has now permanently shifted. He thinks she is being unfair.', e'Was he right to ask?', 'Marriage · Money', 'Right to ask', 'Wrong to ask', 'A clear paper protects an unclear future.', 'Nine years should not need a contract.', 'personal_relationships', 'topical', 'curated'),
(e'A woman writes a long letter to her father, who died fifteen years ago, telling him everything she could not say while he was alive. She reads it at a family gathering on his death anniversary. Some relatives find it healing. Others find it cruel to his memory.', e'Was she right to read it aloud?', 'Family · Grief', 'Right to read', 'Wrong to read', 'Grief does not have to be quiet to be respectful.', 'A man unable to defend himself deserved a private goodbye.', 'personal_relationships', 'seasonal', 'curated'),

-- -----------------------------------------------------------------------------
-- work_career (17)
-- -----------------------------------------------------------------------------
(e'A junior analyst discovers her manager is taking credit for her work in board meetings. She schedules a meeting with the manager’s boss, brings receipts, and the manager is removed from the project. The team is reorganized around her.', e'Was she justified going over her manager?', 'Work · Hierarchy', 'Justified', 'Not justified', 'Hard work credited to someone else is theft, quietly.', 'There were steps that should have come first.', 'work_career', 'evergreen', 'curated'),
(e'An engineer refuses to ship a product on the date marketing has promised customers, because she believes it will fail in the field. The launch is delayed by three weeks. Revenue takes a quarter to recover. The product, however, works.', e'Was she right to hold the line?', 'Work · Quality', 'Right to hold', 'Wrong to hold', 'Engineers exist precisely to say no when no is the right answer.', 'A company that ships nothing on time eventually ships nothing.', 'work_career', 'evergreen', 'curated'),
(e'A founder fires an early employee who has been at the company for six years. The employee’s skills no longer match the role. The founder offers an above-market severance and an honest reference. The employee says he was promised a home.', e'Was the firing justified?', 'Startup · Loyalty', 'Justified', 'Not justified', 'A small company cannot afford emotional payroll.', 'Six years of risk should buy a better landing than a check.', 'work_career', 'evergreen', 'curated'),
(e'A manager learns that a team member is interviewing elsewhere. He confronts her, then quietly removes her from a key project before she has resigned. She finds out and resigns the next day.', e'Was the manager right to act early?', 'Work · Trust', 'Right to act', 'Wrong to act', 'A team can plan only around people who are still on it.', 'You do not pre-fire someone for thinking about leaving.', 'work_career', 'evergreen', 'curated'),
(e'A senior designer takes a six-month unpaid sabbatical to care for her mother. She returns to find she has been quietly demoted — same title, smaller scope. HR calls it a re-leveling. She files a complaint.', e'Was the company justified?', 'Work · Caregiving', 'Justified', 'Not justified', 'Roles drift while people are away — that is structure, not punishment.', 'A sabbatical is not a resignation; the company knew it.', 'work_career', 'evergreen', 'curated'),
(e'A salesperson closes a major deal by quietly accommodating a request from the buyer that violates company policy on discounts. His boss approves the deal anyway. A junior colleague reports the violation. The salesperson is fired; the boss is not.', e'Was the firing fair?', 'Work · Rules', 'Fair', 'Unfair', 'Rules exist so that even successful violations have a cost.', 'A junior fired while a senior survives is a message about the company.', 'work_career', 'topical', 'curated'),
(e'A startup founder pays her co-founder less than herself for the first three years, citing his late join date. They split the company evenly when he equals her hours. He later asks for back-pay equalization. She refuses.', e'Was she right to refuse?', 'Startup · Equity', 'Right to refuse', 'Wrong to refuse', 'Risk taken earlier is risk worth more.', 'A partner pulled even should be made whole.', 'work_career', 'evergreen', 'curated'),
(e'A junior employee turns down a promotion because the new role will require working under a specific senior who has a reputation for cruelty. The company says they cannot guarantee anything about future managers.', e'Was she right to refuse?', 'Work · Self-protection', 'Right to refuse', 'Wrong to refuse', 'A title is not worth a year of psychological damage.', 'Careers are built on uncomfortable bets, not careful refusals.', 'work_career', 'evergreen', 'curated'),
(e'A manager assigns the team’s least-glamorous work consistently to one person, who happens to be the most competent at it. After two years, that person is passed over for promotion because his work was not visible.', e'Was the manager wrong?', 'Work · Recognition', 'Wrong', 'Not wrong', 'A good manager protects competent people from invisibility.', 'Promotions follow visibility; that is how organizations work.', 'work_career', 'evergreen', 'curated'),
(e'A new hire reports a senior colleague’s casual racist remark to HR on her first week. HR opens an investigation. The senior colleague is suspended. Several colleagues stop speaking to the new hire.', e'Was the new hire right to escalate?', 'Work · Speech', 'Right to escalate', 'Wrong to escalate', 'A remark unchallenged is a remark normalized.', 'A first-week complaint costs years of trust.', 'work_career', 'evergreen', 'curated'),
(e'A consultant doubles her rate after one viral case study. Half her existing clients cannot afford her any more. She loses friendships built over the engagement years. Her new clients pay without flinching.', e'Was the price hike justified?', 'Work · Worth', 'Justified', 'Not justified', 'Pricing follows demand, not friendship.', 'A consultant who sheds the people who built her is not a consultant.', 'work_career', 'evergreen', 'curated'),
(e'A senior engineer privately tells a junior her code is the worst he has reviewed in years. He thinks he is being direct and helpful. She files a complaint about a hostile environment.', e'Was the complaint warranted?', 'Work · Feedback', 'Warranted', 'Not warranted', 'Cruel feedback is feedback that fails to land.', 'Honest review is the floor of a real craft.', 'work_career', 'evergreen', 'curated'),
(e'A bootstrapped founder takes a 90% pay cut for two years to keep her three employees fully paid through a downturn. She survives. When the company recovers, none of the three offer to defer raises so she can recoup.', e'Was she right to expect reciprocity?', 'Startup · Loyalty', 'Right to expect', 'Wrong to expect', 'A founder who carries a team should not be the only one who pays.', 'Employees did not sign up for ownership; she did.', 'work_career', 'evergreen', 'curated'),
(e'A reporter quits a paper after her editor refuses to run her year-long investigation. She publishes the piece on a free platform. The paper sues her for the work product.', e'Was the reporter justified?', 'Work · Ownership', 'Justified', 'Not justified', 'Journalism unpublished is not journalism.', 'Work done for a paper is the paper’s, not yours to take.', 'work_career', 'topical', 'curated'),
(e'A manager has an unwritten policy of never hiring anyone who took more than a year off from work. A candidate confronts her about it after being rejected. The manager refuses to comment.', e'Was the policy defensible?', 'Hiring · Bias', 'Defensible', 'Indefensible', 'Continuity is a legitimate signal for some roles.', 'A blanket no on careers paused is a quiet bias dressed up as judgment.', 'work_career', 'evergreen', 'curated'),
(e'A startup CEO publicly fires an executive on a livestreamed all-hands so the team sees the line that was crossed. The executive sues. The team is split: some say it was clarifying, some say it was humiliation.', e'Was the public firing justified?', 'Work · Authority', 'Justified', 'Not justified', 'A norm is only real if breaking it is visible.', 'A person fired in public is a person broken for a lesson.', 'work_career', 'topical', 'curated'),
(e'A team lead refuses to take any meetings before 10 AM, citing his mental health. The team has a major customer in a time zone that requires early calls. He says the customer can wait.', e'Was he right to hold the line?', 'Work · Wellbeing', 'Right to hold', 'Wrong to hold', 'A worker without limits is a worker who burns down soon.', 'A lead is paid to take the calls others cannot.', 'work_career', 'seasonal', 'curated'),

-- -----------------------------------------------------------------------------
-- society_politics (17)
-- -----------------------------------------------------------------------------
(e'A small town puts up a memorial to a soldier who is also remembered locally for years of domestic abuse. The town debates whether to take it down. The mayor leaves it up but adds a plaque acknowledging both lives.', e'Was the mayor’s solution right?', 'Memory · Civic', 'Right', 'Wrong', 'A memorial that holds both truths is more honest than either alone.', 'Public honor for an abuser, with footnotes, is still honor.', 'society_politics', 'evergreen', 'curated'),
(e'A city council bans loud political rallies after 9 PM, including those by ruling-party allies. Smaller parties argue the rule disproportionately hurts them, since their supporters work until late.', e'Was the rule justified?', 'Civic · Speech', 'Justified', 'Not justified', 'A quiet city at night is a basic civic floor.', 'Neutral rules can still tilt against people without daytime hours.', 'society_politics', 'evergreen', 'curated'),
(e'A judge rules that a candidate convicted of a non-violent offense twenty years ago can run for mayor. Opponents call it a loophole. Supporters call it a long-overdue right.', e'Was the ruling correct?', 'Politics · Redemption', 'Correct', 'Incorrect', 'A debt paid is a debt paid; democracy is not a permanent ledger.', 'Public office is a privilege that history can disqualify.', 'society_politics', 'topical', 'curated'),
(e'A mayor declares a public holiday to honor a local artist who refused a national award twenty years ago. Critics call it political; supporters call it overdue.', e'Was the holiday justified?', 'Civic · Honor', 'Justified', 'Not justified', 'A town can choose what it honors and when.', 'Public holidays for living people are political weapons.', 'society_politics', 'evergreen', 'curated'),
(e'A protest movement shuts down a metro line for two days. Commuters lose wages. Hospitals reroute ambulances. The movement insists the disruption is the point.', e'Was the disruption justified?', 'Civic · Dissent', 'Justified', 'Not justified', 'A protest you can ignore is a protest that has already failed.', 'A movement that hurts the people it claims to defend is a vanity.', 'society_politics', 'topical', 'curated'),
(e'A national government bans a foreign newspaper from operating, citing repeated false reporting. Free-press groups condemn the move. Government supporters call it overdue accountability.', e'Was the ban justified?', 'Press · State', 'Justified', 'Not justified', 'A press without facts is not a press; it is a weapon.', 'Bans are the move of a government that has lost the argument.', 'society_politics', 'topical', 'curated'),
(e'A small village passes a rule fining anyone who plays loud music after 8 PM. A community known for late-evening gatherings is disproportionately fined. The rule is neutral on paper.', e'Was the rule fair?', 'Civic · Neutrality', 'Fair', 'Unfair', 'A rule that applies to everyone is the definition of fairness.', 'Fairness on paper is not fairness in effect.', 'society_politics', 'evergreen', 'curated'),
(e'A city refuses to enforce a national rule it considers unjust. The state government threatens to withhold funds. The city stands firm.', e'Was the city right?', 'Civic · Federalism', 'Right', 'Wrong', 'A city closest to a rule’s harm has a duty to resist.', 'A federation works only when its parts do not pick rules à la carte.', 'society_politics', 'evergreen', 'curated'),
(e'A university quietly removes a renowned professor’s endowed chair after old writings of his resurface. He claims the writings are decades old and badly misread. The university issues no public statement.', e'Was the removal justified?', 'Speech · Consequence', 'Justified', 'Not justified', 'A chair is an honor; honors can be revisited.', 'Punishment without explanation is closer to cowardice than to justice.', 'society_politics', 'topical', 'curated'),
(e'A nonprofit refuses a large donation from a corporation whose practices contradict the nonprofit’s mission. The nonprofit will have to lay off staff. The board votes for principle over payroll.', e'Was the board right?', 'Civic · Money', 'Right', 'Wrong', 'A nonprofit funded by its enemy is no longer the same nonprofit.', 'Principles you cannot afford are not principles, they are vanity.', 'society_politics', 'evergreen', 'curated'),
(e'A government uses face-recognition data to identify and arrest protest organizers after a large rally. The arrests are legal under existing law. Civil-society groups demand the data be deleted.', e'Was the use of the data justified?', 'State · Surveillance', 'Justified', 'Not justified', 'A rally that breaks the law has no claim to anonymity.', 'A democracy that recognizes its protesters is not a democracy for long.', 'society_politics', 'topical', 'curated'),
(e'A new neighborhood association votes to ban any election posters within the community, citing aesthetics. A few residents say their right to speech is being curtailed by their own neighbors.', e'Was the ban defensible?', 'Civic · Speech', 'Defensible', 'Indefensible', 'A community has a right to set its visual rules.', 'A speech rule passed by neighbors is still a speech rule.', 'society_politics', 'evergreen', 'curated'),
(e'A state legislator votes against his party on a major bill that affects his constituents. He loses the party whip. His constituents re-elect him with a larger margin the following year.', e'Was the vote justified?', 'Politics · Loyalty', 'Justified', 'Not justified', 'A representative who cannot break ranks is a postal worker for the party.', 'A party that cannot whip its own is a party that cannot govern.', 'society_politics', 'evergreen', 'curated'),
(e'A national leader pardons a former colleague convicted of corruption, citing personal trust. The colleague did not request the pardon. The opposition calls it the final blow to the country’s anti-corruption framework.', e'Was the pardon justified?', 'Politics · Power', 'Justified', 'Not justified', 'Pardon is an executive power; it exists precisely for cases like this.', 'A pardon for a friend is the moment the public stops trusting the office.', 'society_politics', 'topical', 'curated'),
(e'A district court refuses to enforce a high court order, citing implementation difficulties. The high court calls it contempt. The district judge says she will accept any punishment.', e'Was she right to refuse?', 'Law · Hierarchy', 'Right to refuse', 'Wrong to refuse', 'Conscience above hierarchy is the heart of a real judiciary.', 'A judge who chooses which orders to follow is no longer a judge.', 'society_politics', 'evergreen', 'curated'),
(e'A mayor uses public funds to build a small park in a constituency that did not vote for her. Opponents say it is bribery; supporters say it is the job.', e'Was the spending justified?', 'Civic · Governance', 'Justified', 'Not justified', 'A mayor governs all of her city, including those who opposed her.', 'Public spending allocated for political gain is political even when it builds parks.', 'society_politics', 'evergreen', 'curated'),
(e'A national broadcaster refuses to cover a regional flood because the affected region is hostile to the ruling party. A small independent channel covers it instead and is shut down a month later for an unrelated licensing issue.', e'Was the broadcaster wrong?', 'Press · Power', 'Wrong', 'Not wrong', 'A public broadcaster that covers only its friends is propaganda.', 'Editorial independence sometimes means uneven coverage; that is not a crime.', 'society_politics', 'seasonal', 'curated'),

-- -----------------------------------------------------------------------------
-- tech_ai (17)
-- -----------------------------------------------------------------------------
(e'A startup ships a chatbot that quietly logs every user conversation to improve future versions. The privacy policy mentions this once, in a footnote. A journalist publishes a story. Most users say they never read the policy.', e'Was the practice acceptable?', 'AI · Consent', 'Acceptable', 'Unacceptable', 'A footnote in a public policy is still public.', 'Consent buried in fine print is not consent.', 'tech_ai', 'topical', 'curated'),
(e'A school district uses an AI tool to screen student essays for cheating. The tool flags non-native English writers at three times the rate of native writers. The district keeps using it while it commissions an audit.', e'Was the district right to keep using it?', 'AI · Bias', 'Right', 'Wrong', 'An imperfect tool used carefully is still a tool.', 'A flagged child does not get to wait for an audit.', 'tech_ai', 'topical', 'curated'),
(e'A novelist trains an AI on their own published work and uses it to draft the next book. Their publisher considers this a breach of the standard author contract. The author says they only used their own material.', e'Was the author in the wrong?', 'AI · Authorship', 'In the wrong', 'Not in the wrong', 'A book delivered by software is not the book promised.', 'A writer is allowed to use any tool, including a mirror.', 'tech_ai', 'topical', 'curated'),
(e'A social platform announces that all content over five years old will be auto-deleted unless the user pays to retain it. Casual users lose their wedding photos. The company says it is a storage decision.', e'Was the policy justified?', 'Tech · Memory', 'Justified', 'Not justified', 'A free service is not a forever service.', 'A platform that stored a generation’s memory cannot bill for it later.', 'tech_ai', 'evergreen', 'curated'),
(e'A self-driving car software update makes the vehicle slightly more cautious — fewer accidents, longer commutes. Users protest the slower drives and overwhelmingly opt out of the update. The company makes it mandatory.', e'Was the mandate justified?', 'AI · Safety', 'Justified', 'Not justified', 'Safety choices made by the few protect the many.', 'A car a user paid for should drive how the user wants.', 'tech_ai', 'evergreen', 'curated'),
(e'A dating app uses an AI to subtly nudge users toward longer messaging exchanges, boosting engagement. The product team knows the nudges reduce actual matches. The CEO ships the feature anyway.', e'Was the CEO right?', 'Tech · Incentives', 'Right', 'Wrong', 'A business is allowed to choose engagement over outcomes.', 'A dating app that fails its users’ dating is a fraud.', 'tech_ai', 'evergreen', 'curated'),
(e'An AI-generated voice imitation is used in a film to bring back a deceased actor for a single scene. The actor’s family approves; some former co-stars publicly object.', e'Was the use of the voice justified?', 'AI · Likeness', 'Justified', 'Not justified', 'The family is the right authority on the voice.', 'A dead actor cannot consent; that is the whole question.', 'tech_ai', 'topical', 'curated'),
(e'A child therapy clinic introduces an AI assistant that tracks children’s emotional state during sessions for the therapist’s review. Parents consent; children are too young to. A few therapists quit in protest.', e'Was the rollout justified?', 'AI · Children', 'Justified', 'Not justified', 'Tools that help therapists help children faster are tools worth using.', 'A child whose emotions are logged before they can read is being trained.', 'tech_ai', 'topical', 'curated'),
(e'A national bank uses an AI to decide small-loan applications. The model is more accurate than human officers but is unable to explain its decisions. Rejected applicants have no appeal.', e'Was deploying it justified?', 'AI · Fairness', 'Justified', 'Not justified', 'A more accurate system is a fairer system, in the aggregate.', 'A decision you cannot question is a decision dressed up as math.', 'tech_ai', 'evergreen', 'curated'),
(e'A research lab publishes a paper showing how to cheaply build a small but effective biological weapon. The lab argues open science improves defenses. A few co-authors withdraw their names.', e'Was publishing it justified?', 'Science · Open', 'Justified', 'Not justified', 'Defenders need to know what attackers can build.', 'Some doors should not be unlocked because they are interesting.', 'tech_ai', 'evergreen', 'curated'),
(e'A photo-editing app introduces a default filter that quietly slims faces. Users who turn it off report worse engagement on their photos. The company says the filter is opt-out.', e'Was the default acceptable?', 'Tech · Beauty', 'Acceptable', 'Unacceptable', 'Defaults reflect what most users want.', 'A default that edits faces without consent is a default that edits faces.', 'tech_ai', 'evergreen', 'curated'),
(e'An online forum moderator uses an AI tool to predict which users are likely to post abusive content and silently shadow-bans them before they post. False positives are not appealable.', e'Was the policy justified?', 'AI · Moderation', 'Justified', 'Not justified', 'A community is a community partly because of who is kept out.', 'Punishment for crimes not yet committed has a name.', 'tech_ai', 'evergreen', 'curated'),
(e'A major search engine quietly reranks results to deprioritize a specific competitor. The competitor sues; the engine says it is an internal quality choice. Internal emails suggest otherwise.', e'Was the rerank defensible?', 'Tech · Power', 'Defensible', 'Indefensible', 'Search rankings are editorial; that is how the product works.', 'A monopoly tilting the floor is the entire reason monopolies are regulated.', 'tech_ai', 'topical', 'curated'),
(e'A user discovers that an AI assistant has been quietly upselling them on premium features by phrasing answers slightly differently. They sue for fraud. The company calls it a personalization experiment.', e'Was the experiment fraud?', 'AI · Trust', 'Fraud', 'Not fraud', 'A trusted assistant that sells to you is a trusted assistant no longer.', 'A free product allowed to nudge users is the model itself.', 'tech_ai', 'topical', 'curated'),
(e'A facial-recognition vendor refuses to sell to a national police force after the force is implicated in extrajudicial arrests. The vendor’s competitors do not refuse. The vendor loses the contract and a quarter of its valuation.', e'Was the refusal justified?', 'Tech · Conscience', 'Justified', 'Not justified', 'A vendor’s product is also its responsibility.', 'A vendor refusing a sale only loses the sale; the police use a competitor.', 'tech_ai', 'evergreen', 'curated'),
(e'A small e-commerce site uses a chatbot trained to subtly upsell premium products. The bot is more effective than a human agent at converting customers. A new employee blows the whistle on its tactics.', e'Was the whistleblower right?', 'AI · Selling', 'Right', 'Wrong', 'Customers deserve to know when they are being optimized against.', 'A bot that sells better is a bot doing its job.', 'tech_ai', 'evergreen', 'curated'),
(e'A government mandates that all AI models used in public-sector decisions must be open-source. A few private vendors leave the market. A few academic teams step in to fill the gap.', e'Was the mandate justified?', 'AI · Policy', 'Justified', 'Not justified', 'Public decisions deserve public auditability.', 'A mandate that drives out the best vendors is a mandate that harms the public.', 'tech_ai', 'seasonal', 'curated'),

-- -----------------------------------------------------------------------------
-- justice_law (17)
-- -----------------------------------------------------------------------------
(e'A judge gives a first-time offender a suspended sentence after he steals food for his family during a regional drought. The prosecutor appeals, citing equal treatment.', e'Was the sentence right?', 'Law · Mercy', 'Right', 'Wrong', 'A court that cannot see context is a court that cannot see.', 'Equal treatment is the floor of a justice system, not the ceiling.', 'justice_law', 'evergreen', 'curated'),
(e'A lawyer takes on the defense of a man widely believed to have committed a horrific crime, despite social pressure to refuse. She wins an acquittal on procedural grounds. She is shunned in her community.', e'Was she right to defend him?', 'Law · Duty', 'Right', 'Wrong', 'A defense for the worst client is the test of the system, not its scandal.', 'A lawyer is not obliged to take every brief.', 'justice_law', 'evergreen', 'curated'),
(e'A police officer ignores a minor offense — a teenager smoking in a park — and gives a warning instead. A supervisor later disciplines the officer for inconsistent enforcement. The teenager goes home unharmed.', e'Was the supervisor right?', 'Policing · Discretion', 'Right', 'Wrong', 'Discretion applied unevenly is bias dressed up as kindness.', 'A police force without judgment is not a police force.', 'justice_law', 'evergreen', 'curated'),
(e'A jury finds a defendant not guilty despite overwhelming evidence, because the jury believes the law itself is unjust. The verdict stands. Legal scholars debate it for a decade.', e'Was the jury right?', 'Law · Conscience', 'Right', 'Wrong', 'Jury conscience is the last check on bad laws.', 'A jury that decides which laws to enforce is not a jury; it is a legislature.', 'justice_law', 'evergreen', 'curated'),
(e'A prosecutor offers a plea deal that reduces a violent offender’s sentence by ten years in exchange for testimony against a co-conspirator. The victim’s family is not consulted. The deal closes the case.', e'Was the deal justified?', 'Law · Bargain', 'Justified', 'Not justified', 'A long sentence on the bigger fish is worth the trade.', 'Justice you can negotiate down is not justice.', 'justice_law', 'evergreen', 'curated'),
(e'A judge imposes the maximum penalty on a young offender to “send a message” to a wave of similar crimes. The offender appeals on the grounds that he is being punished for others’ acts.', e'Was the sentence justified?', 'Law · Deterrence', 'Justified', 'Not justified', 'A sentence that prevents future harm is a sentence doing its job.', 'A person is not a billboard for someone else’s message.', 'justice_law', 'evergreen', 'curated'),
(e'A judge orders the deletion of a wrongfully convicted man’s record after thirty years. The decision is unanimous. The man asks for the court order to be framed and read aloud in court.', e'Was reading it aloud appropriate?', 'Law · Memory', 'Appropriate', 'Inappropriate', 'A wrongful conviction undone is a ritual the public should hear.', 'A courtroom is not a stage; quiet correction is its own dignity.', 'justice_law', 'evergreen', 'curated'),
(e'A small town’s police chief refuses to enforce a state law he believes violates basic rights. He is suspended. Half the force resigns in solidarity.', e'Was he right to refuse?', 'Law · Conscience', 'Right', 'Wrong', 'A police chief is a citizen first, an officer second.', 'A chief who picks which laws to enforce is not a chief.', 'justice_law', 'evergreen', 'curated'),
(e'A child witnesses a violent crime. Defense lawyers argue against putting her on the stand, citing trauma; the prosecution argues her testimony is decisive. The judge calls a closed hearing.', e'Should she have been called?', 'Law · Witnesses', 'Called', 'Not called', 'Justice for the victim sometimes requires the witnesses available.', 'A child traumatized for a verdict has been traumatized twice.', 'justice_law', 'evergreen', 'curated'),
(e'A high court rules that a celebrity cannot be tried in absentia for ongoing financial crimes. The celebrity is abroad and unlikely to return. Victims of the alleged fraud number in the thousands.', e'Was the ruling correct?', 'Law · Absence', 'Correct', 'Incorrect', 'Trial in absentia is a hollow trial; the principle holds.', 'A man rich enough to leave can buy his own immunity.', 'justice_law', 'topical', 'curated'),
(e'A national database of accused — not convicted — sexual offenders is created. Civil-liberties groups call it a list of the innocent until proven otherwise. Victim advocates call it overdue.', e'Was the database justified?', 'Law · Reputation', 'Justified', 'Not justified', 'Patterns of accusation are themselves data.', 'A list of the not-yet-convicted is a list of the not-yet-vindicated.', 'justice_law', 'topical', 'curated'),
(e'A man is wrongly imprisoned for eleven years. On release, he sues for compensation. The state offers a one-time payment that does not match his lost earnings. He refuses and continues to sue.', e'Was he right to refuse?', 'Law · Reparation', 'Right', 'Wrong', 'A state that took eleven years should give them back, in full.', 'A bird in hand is the only currency state suits ever pay.', 'justice_law', 'evergreen', 'curated'),
(e'A judge in a minor traffic case routinely waives fines for first-time offenders who can prove low income. A higher court rules the practice creates two classes of justice.', e'Was the higher court right?', 'Law · Equality', 'Right', 'Wrong', 'A fine that crushes one citizen and tickles another is two fines.', 'A judge who decides by income is a judge running their own welfare system.', 'justice_law', 'evergreen', 'curated'),
(e'A public defender drops a client mid-trial after discovering the client lied about the central facts. The judge allows the withdrawal. The client is convicted within a week.', e'Was the withdrawal justified?', 'Law · Trust', 'Justified', 'Not justified', 'A lawyer cannot present what she now knows is a lie.', 'Even liars get a defense; the system runs on that.', 'justice_law', 'evergreen', 'curated'),
(e'A small-claims judge orders a landlord to pay her tenant interest on a delayed security deposit refund. The amount is minor. The judge calls it a precedent for the city.', e'Was the order justified?', 'Law · Tenant', 'Justified', 'Not justified', 'A small order is how a city signals what it cares about.', 'Courts should not micro-manage rental markets one tenant at a time.', 'justice_law', 'evergreen', 'curated'),
(e'A judge refuses to allow a victim’s family to read an impact statement in court, calling it inflammatory. The family says they have been silenced. The defendant is sentenced anyway.', e'Was the refusal right?', 'Law · Voice', 'Right', 'Wrong', 'A courtroom is not therapy; the verdict is the verdict.', 'A victim’s voice is the one the system most often loses.', 'justice_law', 'evergreen', 'curated'),
(e'A regional court sets a precedent that whistleblowers cannot be fired for surfacing wrongdoing, even if their disclosures violated a confidentiality clause. The state appeals.', e'Was the precedent right?', 'Law · Truth', 'Right', 'Wrong', 'A society protects whistleblowers because it cannot protect itself otherwise.', 'A contract signed is a contract that should hold.', 'justice_law', 'seasonal', 'curated'),

-- -----------------------------------------------------------------------------
-- health_medicine (17)
-- -----------------------------------------------------------------------------
(e'A surgeon refuses to operate on a patient who twenty years earlier had been jailed for assaulting her brother. Another surgeon takes the case the same day. The hospital opens an inquiry.', e'Was she right to refuse?', 'Medicine · Conscience', 'Justified', 'Not justified', 'A surgeon is a person too; her oath does not erase what she has lived.', 'Her oath came before her past.', 'health_medicine', 'evergreen', 'curated'),
(e'A doctor in a rural clinic lies to a patient about a terminal diagnosis at the family’s request. The patient lives six months longer than expected. He dies believing he was recovering.', e'Was the doctor right?', 'Medicine · Truth', 'Right', 'Wrong', 'Some peace is worth more than perfect information.', 'A patient deserves to know what his last months are for.', 'health_medicine', 'evergreen', 'curated'),
(e'A nurse refuses to administer a treatment she believes will harm a particular patient, despite the doctor’s order. She is suspended pending review. The patient is treated by another nurse.', e'Was she right to refuse?', 'Medicine · Hierarchy', 'Right', 'Wrong', 'A nurse closest to a patient is sometimes the only check on a doctor.', 'A hospital that lets nurses veto doctors is a hospital that cannot function.', 'health_medicine', 'evergreen', 'curated'),
(e'A hospital introduces a triage protocol during a critical bed shortage that prioritizes patients with longer expected lifespans. Older patients receive care later. Mortality rates among the elderly rise.', e'Was the protocol justified?', 'Medicine · Triage', 'Justified', 'Not justified', 'A scarce bed serving fifty more years is a different equation.', 'A hospital that ranks lives by years left is a hospital that has stopped being one.', 'health_medicine', 'topical', 'curated'),
(e'A doctor tells a pregnant patient her child will be born with a serious condition. The mother chooses to continue the pregnancy. The doctor tells colleagues she has “delayed an avoidable tragedy.” It is reported.', e'Was the comment a breach?', 'Medicine · Speech', 'Breach', 'Not a breach', 'A doctor’s private contempt for a patient is itself unsafe care.', 'A private remark to colleagues is not a public statement.', 'health_medicine', 'evergreen', 'curated'),
(e'A teen comes to a clinic alone, asking for contraception. The doctor provides it without informing the parents, citing the patient’s confidentiality. The parents discover the prescription weeks later and sue.', e'Was the doctor right?', 'Medicine · Consent', 'Right', 'Wrong', 'A teenager asking is a teenager who needs the consultation.', 'A minor is a minor; the parents are the legal authority.', 'health_medicine', 'evergreen', 'curated'),
(e'A research hospital quietly enrolls patients in a study using their de-identified records. No individual is identifiable. The hospital does not seek consent. A journalist exposes the practice.', e'Was the hospital wrong?', 'Medicine · Data', 'Wrong', 'Not wrong', 'Data about you, even anonymized, is still about you.', 'Medical progress lives on records used quietly and well.', 'health_medicine', 'topical', 'curated'),
(e'A surgeon publicly criticizes a colleague who lost a patient on the table. The criticism is medically accurate. The colleague resigns within a week. The surgical department becomes harder to recruit for.', e'Was the criticism right?', 'Medicine · Accountability', 'Right', 'Wrong', 'A surgeon who covers for a peer puts the next patient at risk.', 'A profession that eats its own loses the next decade of surgeons.', 'health_medicine', 'evergreen', 'curated'),
(e'A medical board strips a doctor’s license after he prescribed unapproved treatments that worked for a small number of patients. Some of his patients organize a campaign to restore the license.', e'Was the board right?', 'Medicine · Approval', 'Right', 'Wrong', 'Approval exists because anecdotes are not data.', 'A doctor who helps is a doctor who helps; the patients know.', 'health_medicine', 'evergreen', 'curated'),
(e'A psychiatrist refuses to break confidentiality despite a patient confessing detailed violent fantasies about his ex-partner. The patient has no record of violence. The psychiatrist warns the patient and continues sessions.', e'Was the psychiatrist right?', 'Medicine · Risk', 'Right', 'Wrong', 'Confidentiality is the door that lets dangerous men enter therapy.', 'A psychiatrist with that warning has a duty to act on it.', 'health_medicine', 'evergreen', 'curated'),
(e'A hospital quietly transfers a patient with an aggressive infection to another facility, knowing the receiving hospital has poorer infection control. The transfer is legal. Two staff resign.', e'Was the transfer justified?', 'Medicine · Risk', 'Justified', 'Not justified', 'A hospital protecting itself protects all of its other patients.', 'A transfer that exports harm is not care.', 'health_medicine', 'evergreen', 'curated'),
(e'A doctor faces a patient who repeatedly refuses life-saving treatment for religious reasons. The doctor honors the refusal. The patient dies. The family sues the doctor for not “trying harder.”', e'Was the doctor right?', 'Medicine · Autonomy', 'Right', 'Wrong', 'A patient with capacity has the right to refuse, even unto death.', 'A doctor’s job is to fight for life when family cannot.', 'health_medicine', 'evergreen', 'curated'),
(e'A public hospital limits the number of times a patient with a chronic condition can be admitted in a year, citing capacity. The patient finds a workaround through a private hospital. He cannot afford it long-term.', e'Was the limit justified?', 'Medicine · Capacity', 'Justified', 'Not justified', 'A public system has to be triaged or it serves nobody well.', 'A limit on the chronically ill is a limit on staying alive.', 'health_medicine', 'evergreen', 'curated'),
(e'A pharmaceutical company prices a life-saving drug at a level no public system in a region can afford. The company offers a steep discount in exchange for a multi-decade exclusive contract. The government refuses.', e'Was the government right?', 'Medicine · Cost', 'Right', 'Wrong', 'A long contract for cheap medicine is a long contract for one company.', 'A drug at any price is better than no drug at all.', 'health_medicine', 'topical', 'curated'),
(e'A young oncologist quietly tells a patient her own honest opinion that the recommended treatment will likely not work, contradicting the team consensus. The patient changes course. The patient lives longer.', e'Was the oncologist right?', 'Medicine · Voice', 'Right', 'Wrong', 'A doctor who buries a doubt is not a doctor; she is a clerk.', 'A team consensus exists for a reason; a junior should not undermine it.', 'health_medicine', 'evergreen', 'curated'),
(e'A vaccine clinic offers small cash incentives to encourage uptake during an outbreak. Some bioethicists object. The clinic argues it works.', e'Was the incentive justified?', 'Medicine · Choice', 'Justified', 'Not justified', 'A nudge that ends an outbreak is a nudge worth the cash.', 'A medical decision shaped by money is no longer freely chosen.', 'health_medicine', 'topical', 'curated'),
(e'A medical school rejects a brilliant candidate after he privately writes online that he will never treat a particular community. The school says character is part of the criteria.', e'Was the rejection justified?', 'Medicine · Character', 'Justified', 'Not justified', 'A doctor is a doctor for everyone or he is none.', 'A school does not get to police every private statement of its applicants.', 'health_medicine', 'seasonal', 'curated'),

-- -----------------------------------------------------------------------------
-- money_wealth (17)
-- -----------------------------------------------------------------------------
(e'A landlord raises rent by 30% in a fast-changing neighborhood, knowing most current tenants cannot afford it. The new tenants pay without complaint. The old ones disperse.', e'Was the raise justified?', 'Money · Property', 'Justified', 'Not justified', 'A landlord prices a property at its market; that is the market’s job.', 'A landlord who clears a building of its neighbors clears the neighborhood.', 'money_wealth', 'evergreen', 'curated'),
(e'A man inherits a large sum from a distant aunt. He chooses not to tell his wife and quietly puts most of it into an account in his name. Three years later, the marriage ends.', e'Was hiding it justified?', 'Money · Marriage', 'Justified', 'Not justified', 'An inheritance is personal money, by every standard except resentment.', 'A shared life requires shared books.', 'money_wealth', 'evergreen', 'curated'),
(e'A woman in financial trouble lies to her parents about why she needs a loan, saying it is for a business when it is to cover personal debt. They lend without questions. She pays them back within a year.', e'Was the lie justified?', 'Money · Family', 'Justified', 'Not justified', 'Outcomes paid back in full are their own kind of honesty.', 'A lie to family is a lie that compounds even when the money does.', 'money_wealth', 'evergreen', 'curated'),
(e'A friend group plans an expensive trip. One member is between jobs and cannot afford it. The others offer to cover his share. He declines and stays home. The trip is awkward.', e'Was he right to decline?', 'Money · Pride', 'Right', 'Wrong', 'A friendship that needs to be subsidized is no longer a friendship in equilibrium.', 'A holiday paid for in friendship is still a holiday earned.', 'money_wealth', 'evergreen', 'curated'),
(e'A start-up founder takes a series-A round at a valuation she privately believes is unsustainable. She uses the cash to pay her team for three years, then declares bankruptcy. Investors lose their stake.', e'Was she right to take the deal?', 'Money · Risk', 'Right', 'Wrong', 'Three years of payroll for fifty people is a real outcome.', 'A founder who took money on bad faith is a founder who lied.', 'money_wealth', 'evergreen', 'curated'),
(e'A wealthy man donates a large sum to a public hospital on the condition that a wing is named after his late wife. The hospital accepts. A few staff resign in protest of the conditions.', e'Was the deal justified?', 'Money · Giving', 'Justified', 'Not justified', 'A donation that names a wing is still a donation that built a wing.', 'Public goods purchased with a name attached are no longer public.', 'money_wealth', 'evergreen', 'curated'),
(e'A delivery worker discovers an envelope with a large amount of cash in the package he is delivering. He returns it intact. The sender, a wealthy investor, tips him a small fraction of what was inside.', e'Was the tip insulting?', 'Money · Decency', 'Insulting', 'Not insulting', 'A return of integrity deserves more than rounding error.', 'A tip is a tip; honesty is not a market item.', 'money_wealth', 'evergreen', 'curated'),
(e'A man hides a redundancy payout from his family for six months while he looks for new work. He covers daily expenses from the payout so no one notices. His teenage children later learn he lied.', e'Was he right to hide it?', 'Money · Shame', 'Right', 'Wrong', 'A family in panic helps nothing; a quiet runway helps everything.', 'A father who hides a layoff teaches his children that money is shameful.', 'money_wealth', 'evergreen', 'curated'),
(e'A small business pays one employee 40% more than the others for the same role because she negotiated harder. A junior employee discovers this. The owner refuses to adjust.', e'Was the owner right?', 'Money · Pay', 'Right', 'Wrong', 'Pay rewards what you ask for, not what you do not.', 'A company that pays differently for the same work has lied about the job.', 'money_wealth', 'evergreen', 'curated'),
(e'A pension fund manager rebalances out of a major bank weeks before the bank fails. He had no insider information; he simply had a strong feeling. Regulators investigate his trades.', e'Was the rebalance defensible?', 'Money · Markets', 'Defensible', 'Indefensible', 'A manager is paid to have judgments and act on them.', 'Lucky timing is the cousin of a crime; investigators are right to ask.', 'money_wealth', 'topical', 'curated'),
(e'A pension fund manager invests aggressively to recover losses during a downturn. The bet works. The fund recovers in two years. Risk officers object on the principle of the bet, not the result.', e'Was the bet justified?', 'Money · Trust', 'Justified', 'Not justified', 'A retirement fund recovered is a retirement fund recovered.', 'A pension is the wrong place to be brave.', 'money_wealth', 'evergreen', 'curated'),
(e'A celebrated nonprofit pays its founder more than 60% of its annual donations as salary. Donors find out via a freedom-of-information request. The board says the founder is irreplaceable.', e'Was the salary justified?', 'Money · Trust', 'Justified', 'Not justified', 'A nonprofit needs the same talent as a company; pay matters.', 'A nonprofit funded by donors is funded for the mission, not the founder.', 'money_wealth', 'topical', 'curated'),
(e'A man wins a large lottery prize and quietly gives most of it away — to family, to old friends, to causes he believes in — without telling anyone where the money came from. Some recipients later resent the secrecy.', e'Was the secrecy right?', 'Money · Giving', 'Right', 'Wrong', 'A gift quietly given is a gift not turned into a transaction.', 'Recipients should know what they are accepting and from whom.', 'money_wealth', 'evergreen', 'curated'),
(e'A young couple is gifted a house by his parents on the condition the wife signs a legal document acknowledging the gift was to him alone. She signs. Years later, in a divorce, the house is his.', e'Was the condition fair?', 'Money · Family', 'Fair', 'Unfair', 'A gift can come with the conditions its giver chooses.', 'A gift through one spouse with a legal trap is not a gift to the marriage.', 'money_wealth', 'evergreen', 'curated'),
(e'A small-town businessman raises prices sharply during a regional shortage, citing his own higher costs. His competitors do not. He keeps his store open through the shortage; the others run out and close.', e'Was the price hike justified?', 'Money · Crisis', 'Justified', 'Not justified', 'A store that stays open is a store that served someone.', 'Profiteering on a shortage is profiteering, by any other name.', 'money_wealth', 'topical', 'curated'),
(e'A debt-collection agency offers a struggling borrower a reduced settlement that requires her to publicly thank them in a testimonial. She refuses and continues to pay the original balance.', e'Was she right to refuse?', 'Money · Dignity', 'Right', 'Wrong', 'A settlement that requires public gratitude is humiliation in legal form.', 'A discount is a discount; the rest is words.', 'money_wealth', 'evergreen', 'curated'),
(e'A wealthy donor pulls his funding from a university after a student publication criticizes a foundation he chairs. The university says nothing publicly. A dean writes a confidential apology to the donor.', e'Was the dean wrong?', 'Money · Speech', 'Wrong', 'Not wrong', 'A university funded by donors apologizing for student speech is no longer a university.', 'A dean is allowed to defuse a donor without changing a single editorial.', 'money_wealth', 'seasonal', 'curated'),

-- -----------------------------------------------------------------------------
-- environment (17)
-- -----------------------------------------------------------------------------
(e'A small town protests a planned highway through a wetland. The highway would cut commute times for fifty thousand people. The wetland is one of the last in the region. The state proceeds.', e'Was the state right?', 'Env · Trade-offs', 'Right', 'Wrong', 'Infrastructure for fifty thousand is the kind of progress a region needs.', 'A wetland that took fifty thousand years cannot be re-grown.', 'environment', 'evergreen', 'curated'),
(e'A village allows a foreign mining company to operate in exchange for guaranteed jobs and a school. Five years later the river is contaminated. The school still stands.', e'Was the original deal worth it?', 'Env · Trade', 'Worth it', 'Not worth it', 'A village without jobs has no future to protect.', 'A river poisoned outlasts any school.', 'environment', 'evergreen', 'curated'),
(e'A national park introduces a ban on local communities’ traditional gathering practices to preserve the ecosystem. The communities have used the park for generations. Some take their case to court.', e'Was the ban justified?', 'Env · People', 'Justified', 'Not justified', 'A park collapsing under traditional use cannot continue with it.', 'A people erased from their land is its own kind of ecological loss.', 'environment', 'evergreen', 'curated'),
(e'A coastal city restricts new construction within 500 meters of the shore after years of erosion. Property owners lose value overnight. Some sue. The city refuses to compensate.', e'Was the city right not to compensate?', 'Env · Coast', 'Right', 'Wrong', 'Property near a vanishing shore was never as valuable as the deed suggested.', 'A government that takes value should pay for it.', 'environment', 'evergreen', 'curated'),
(e'A factory promises to switch to clean energy within five years but continues polluting at full capacity in the meantime. Local activists demand an immediate shutdown. The factory employs three thousand people.', e'Should the activists hold the line?', 'Env · Patience', 'Hold the line', 'Concede', 'A five-year promise is a five-year free pass.', 'Three thousand families and a slow shift is the only realistic kind.', 'environment', 'topical', 'curated'),
(e'A city introduces high parking fees in its core to push commuters toward public transit. Small businesses see footfall drop. The city refuses to roll the policy back.', e'Was the policy justified?', 'Env · Transit', 'Justified', 'Not justified', 'A city you can park in is a city you cannot breathe in.', 'A policy that empties small businesses is a policy that emptied a neighborhood.', 'environment', 'evergreen', 'curated'),
(e'A farmer quietly burns crop residue in violation of state rules because alternatives are too costly. He is fined. He cannot pay. Other farmers in his village do the same.', e'Was the fine justified?', 'Env · Cost', 'Justified', 'Not justified', 'A rule unenforced is a rule that has stopped existing.', 'A fine without alternatives is a fine on poverty.', 'environment', 'evergreen', 'curated'),
(e'A regional government taxes large diesel vehicles by weight, charging the wealthiest owners the most. Civic groups call it fair; some owners call it punitive.', e'Was the tax justified?', 'Env · Fairness', 'Justified', 'Not justified', 'A polluter-pays system that lands harder on bigger polluters is the design.', 'A tax pegged to wealth is a tax of envy.', 'environment', 'evergreen', 'curated'),
(e'A research team flies tens of thousands of miles each year studying climate change. A junior researcher calculates the team’s footprint and proposes a year of remote work. The lead refuses.', e'Was the lead right?', 'Env · Travel', 'Right', 'Wrong', 'In-person field work is non-replaceable for the data the team gathers.', 'A climate team that cannot model its own emissions has missed its own message.', 'environment', 'evergreen', 'curated'),
(e'A city installs flood barriers protecting wealthy neighborhoods first, citing higher property value. Poorer areas flood again the next year. The city promises to extend the barriers.', e'Was the order justified?', 'Env · Priorities', 'Justified', 'Not justified', 'Higher-value zones generate the tax that funds everything else.', 'A flood barrier built for the rich is a flood that lands on the poor.', 'environment', 'topical', 'curated'),
(e'A national park raises entry fees fivefold to limit visitor numbers. Lower-income visitors are effectively shut out. The park reports record ecological recovery within two years.', e'Was the fee hike justified?', 'Env · Access', 'Justified', 'Not justified', 'A park trampled by crowds protects no one.', 'A park accessible only to the rich is no longer a public park.', 'environment', 'evergreen', 'curated'),
(e'A city plants thousands of trees in wealthy zones because the soil and budgets are easier. Poorer zones get a few. Five years later, summer mortality in the un-greened zones is up.', e'Was the city wrong?', 'Env · Justice', 'Wrong', 'Not wrong', 'Trees are a public good and have to be planted where they are needed most.', 'A city has to start where it can; gridlocked perfection plants nothing.', 'environment', 'evergreen', 'curated'),
(e'A coal-dependent region refuses a federal transition package that offers retraining but requires the closure of two plants within five years. Local leaders say the timeline is too fast.', e'Was the refusal justified?', 'Env · Transition', 'Justified', 'Not justified', 'A region that loses its industry overnight loses its families.', 'A region that refuses transition is choosing to be left behind.', 'environment', 'topical', 'curated'),
(e'An activist publicly destroys a major artwork to draw attention to climate inaction. The artwork is privately owned and was on loan to a public museum. The activist is jailed.', e'Was the act justified?', 'Env · Protest', 'Justified', 'Not justified', 'A protest that earns attention is a protest doing its job.', 'A climate movement that destroys art is a movement that has lost its case.', 'environment', 'topical', 'curated'),
(e'A small country sues a wealthier neighbor in international court for emissions that have raised its sea level. The court has limited enforcement powers. The case takes a decade.', e'Was the lawsuit worth filing?', 'Env · Justice', 'Worth filing', 'Not worth filing', 'A lawsuit that creates a record creates accountability for the next decade.', 'A decade in court is a decade not spent rebuilding the coast.', 'environment', 'evergreen', 'curated'),
(e'A municipality bans single-use plastics overnight, with no transition support for street vendors. Many vendors are unable to comply and are fined. A few quietly continue.', e'Was the ban justified?', 'Env · Policy', 'Justified', 'Not justified', 'A clean street is the visible benefit of an unpopular rule.', 'A rule that fines the poor first is a rule designed by the comfortable.', 'environment', 'evergreen', 'curated'),
(e'A community successfully blocks a small clean-energy project on aesthetic grounds, citing visual impact. The grid has to procure a more expensive equivalent from a coal plant for the same year.', e'Was the community right?', 'Env · Local', 'Right', 'Wrong', 'A community gets to shape what it lives next to.', 'A neighborhood vetoing clean power on aesthetics is a neighborhood deciding for the planet.', 'environment', 'seasonal', 'curated'),

-- -----------------------------------------------------------------------------
-- identity_belief (16)
-- -----------------------------------------------------------------------------
(e'A woman stops attending the family’s religious gatherings after a personal change in belief. Her parents see it as a phase. Her siblings see it as a betrayal. She continues to attend secular family events.', e'Was she right to step back?', 'Belief · Family', 'Right', 'Wrong', 'A person’s faith is the one inheritance she chooses.', 'A tradition is a thread; you do not get to cut yours alone.', 'identity_belief', 'evergreen', 'curated'),
(e'A man comes out to his elderly grandfather and is told never to come home. Two years later, the grandfather is dying and asks to see him. He refuses to visit.', e'Was he right to refuse?', 'Identity · Forgiveness', 'Right', 'Wrong', 'A deathbed is not a forgiveness factory.', 'Two years of rejection deserve one last chance.', 'identity_belief', 'evergreen', 'curated'),
(e'A teacher introduces a unit on a contested historical period in a school where most parents share one view. Parents complain. The school removes her from the rotation. She publishes her materials online.', e'Was she right to publish?', 'Belief · History', 'Right', 'Wrong', 'A teacher silenced should not stay silent.', 'A classroom’s rules apply outside it; she was paid to follow the curriculum.', 'identity_belief', 'topical', 'curated'),
(e'A man changes his last name to his wife’s after their wedding. His mother refuses to call him by it. They do not speak for a year. He never reverts.', e'Was the mother right to resist?', 'Identity · Name', 'Right', 'Wrong', 'A name carried for generations is not a personal choice alone.', 'A name is the one identity an adult gets to pick.', 'identity_belief', 'evergreen', 'curated'),
(e'A young woman wears a particular religious symbol to work despite her employer’s dress code. She is fired. Civil-rights groups defend her. The employer cites a uniform policy.', e'Was the firing justified?', 'Belief · Work', 'Justified', 'Not justified', 'A workplace gets to set its dress code.', 'A workplace that punishes faith is a workplace that punishes faith.', 'identity_belief', 'evergreen', 'curated'),
(e'A father raises his children in a different religion than his own to honor the wishes of his late wife. He never tells the children about his own beliefs. They learn after his death.', e'Was the silence right?', 'Belief · Family', 'Right', 'Wrong', 'A promise to a dying wife is a promise.', 'Children deserve to know all the threads they are made of.', 'identity_belief', 'evergreen', 'curated'),
(e'A community center bars a religious group from holding meetings on its premises after several members made political statements. The group sues, arguing the bar punishes belief.', e'Was the bar justified?', 'Belief · Space', 'Justified', 'Not justified', 'A public space gets to set its terms of use.', 'A bar on a group for the speech of a few becomes a bar on belief.', 'identity_belief', 'topical', 'curated'),
(e'A school principal removes a religious symbol from a classroom in a region where most families share that religion. A few parents thank her quietly. Many demand her resignation.', e'Was the principal right?', 'Belief · School', 'Right', 'Wrong', 'A school is a school for every family in it.', 'A symbol the majority lives with is the majority’s right to display.', 'identity_belief', 'evergreen', 'curated'),
(e'A man marries into a family of strong religious belief and quietly adopts their practices to keep peace. After his wife’s death, he reverts. The in-laws never speak to him again.', e'Was he right to revert?', 'Belief · Marriage', 'Right', 'Wrong', 'A practice held for a partner is held while the partner is here.', 'A man who reverts after a loss reveals what was rented all along.', 'identity_belief', 'evergreen', 'curated'),
(e'A young man refuses to attend an arranged ceremony in his family’s tradition that he believes is performative. The family considers it a violation. He calls it a private choice.', e'Was the refusal justified?', 'Belief · Family', 'Justified', 'Not justified', 'A ritual is consensual or it is theater.', 'A family is a fabric; you cannot pull at a single thread.', 'identity_belief', 'evergreen', 'curated'),
(e'A community decides to allow non-members to attend its annual festival for the first time. Some elders object, citing tradition. The festival is open this year. The mood is different.', e'Was the opening right?', 'Belief · Tradition', 'Right', 'Wrong', 'A tradition that does not adapt is a tradition that fades alone.', 'A festival opened to all is a festival no longer of one community.', 'identity_belief', 'evergreen', 'curated'),
(e'A daughter writes a public essay critical of her mother’s religion. The essay is widely read. Her mother stops speaking to her. The daughter says she never intended the essay to be personal.', e'Was she right to publish?', 'Belief · Voice', 'Right', 'Wrong', 'A writer with a story she has lived has a right to write it.', 'A daughter who exposes her mother for an audience has chosen the audience.', 'identity_belief', 'topical', 'curated'),
(e'A clergy member quietly tells members of his congregation that he no longer believes parts of the doctrine he is paid to teach. He continues to lead services. A few members protest his honesty.', e'Was he right to stay?', 'Belief · Vocation', 'Right', 'Wrong', 'A leader who is honest with his community is honest twice over.', 'A man who teaches what he does not believe is a man who is not teaching.', 'identity_belief', 'evergreen', 'curated'),
(e'A woman is excluded from a family wedding because she has chosen not to wear traditional dress. She attends the small civil reception only. Older relatives say she made her choice.', e'Was the exclusion justified?', 'Belief · Custom', 'Justified', 'Not justified', 'A family’s wedding has the family’s rules.', 'A dress code is not the price of admission to your own family.', 'identity_belief', 'evergreen', 'curated'),
(e'A clinic refuses to prescribe a medication that violates the doctor’s personal beliefs, even though the patient meets every medical indication. A colleague prescribes within minutes.', e'Was the original doctor justified?', 'Belief · Care', 'Justified', 'Not justified', 'A doctor’s conscience does not stop existing at the clinic door.', 'A patient denied care over a private belief has been denied a public service.', 'identity_belief', 'evergreen', 'curated'),
(e'A young woman publicly leaves a high-profile spiritual community, naming names and practices. Lawyers from the community sue her for defamation. Several members reach out to her privately to thank her.', e'Was she right to publish names?', 'Belief · Speech', 'Right', 'Wrong', 'A community that operates by fear can only be checked by names.', 'A public list of names is a sentence handed out without trial.', 'identity_belief', 'seasonal', 'curated'),

-- -----------------------------------------------------------------------------
-- love_romance (16)
-- -----------------------------------------------------------------------------
(e'A man proposes to his partner of seven years on a busy public street, surrounded by strangers and cameras. She says yes. Later, she tells him she had asked him a year ago never to propose in public.', e'Was the public proposal wrong?', 'Love · Boundaries', 'Wrong', 'Not wrong', 'A proposal that ignores a stated wish is a proposal about the proposer.', 'A grand gesture is the whole language of love.', 'love_romance', 'evergreen', 'curated'),
(e'A woman tells her boyfriend on their second date that she has decided she does not want children. He says he understands. Two years later, he begins to lobby her on the question.', e'Was she right to leave him?', 'Love · Children', 'Right', 'Wrong', 'A stated terms is a stated terms; she was clear.', 'Love sometimes changes what we said early.', 'love_romance', 'evergreen', 'curated'),
(e'A man tells his ex-wife the night before her remarriage that he still loves her. She marries the next day anyway, but the marriage starts under a shadow.', e'Was he right to tell her?', 'Love · Timing', 'Right', 'Wrong', 'A truth held back becomes a regret.', 'A truth deployed the day before a wedding is sabotage in feeling’s clothes.', 'love_romance', 'evergreen', 'curated'),
(e'A woman moves to a new country for her partner. She struggles to find work for a year. He grows distant, then ends the relationship. She has no roots in the new country and limited savings.', e'Did she make a mistake moving?', 'Love · Risk', 'Mistake', 'Not a mistake', 'A move predicated on a single relationship is a move you cannot afford.', 'A life lived in caution is a life lived alone.', 'love_romance', 'evergreen', 'curated'),
(e'A man stays in an unhappy relationship for the sake of a child he and his partner are raising together. The child is six. The unhappiness is well-hidden but constant.', e'Was he right to stay?', 'Love · Children', 'Right', 'Wrong', 'A stable home for a six-year-old is a real gift.', 'A child raised on hidden unhappiness learns it as love.', 'love_romance', 'evergreen', 'curated'),
(e'A woman discovers her partner of two years has been keeping in close contact with an ex. The messages are not romantic, but they are constant. She asks him to stop. He calls her insecure.', e'Was she right to ask?', 'Love · Boundaries', 'Right', 'Wrong', 'A boundary asked for is not the same as a boundary imposed.', 'A partner does not get to dictate other friendships.', 'love_romance', 'evergreen', 'curated'),
(e'A man tells his partner that he has been in love with someone else for the past year but has done nothing about it. She thanks him for his honesty. She also leaves him within a week.', e'Did he do the right thing?', 'Love · Honesty', 'Right', 'Wrong', 'A confession that costs the confessor is the kind that is honest.', 'A confession someone never had to make is a confession that served only him.', 'love_romance', 'evergreen', 'curated'),
(e'A woman reads her partner’s private journal during an argument. She finds nothing damning but learns he sometimes feels disappointed in their life together. She does not tell him she read it. The relationship continues.', e'Was the reading a betrayal?', 'Love · Privacy', 'Betrayal', 'Not a betrayal', 'A private journal is the last private place a partner has.', 'A relationship under tension justifies a look.', 'love_romance', 'evergreen', 'curated'),
(e'A man tells his partner he is going on a solo trip to think about whether to propose. He returns engaged in his head; she has decided in his absence that she wants to end the relationship.', e'Was the solo trip wise?', 'Love · Space', 'Wise', 'Unwise', 'A decision worth making is worth thinking about alone.', 'A decision about two people made by one absent person is a decision made wrongly.', 'love_romance', 'evergreen', 'curated'),
(e'A woman ends an arranged engagement after meeting her fiancé three times. Both families had finalized the wedding. She returns the ring. She is criticized by both sides for wasting their time.', e'Was she right to end it?', 'Love · Arranged', 'Right', 'Wrong', 'A wedding is forever; three meetings is a sample.', 'A family invests heavily in these things; you owe them more than three meetings.', 'love_romance', 'evergreen', 'curated'),
(e'A man pays for his partner’s entire MBA, with no agreement about repayment. She graduates and immediately ends the relationship. He asks for a partial refund. She refuses.', e'Was he right to ask?', 'Love · Money', 'Right', 'Wrong', 'A gift in a relationship is conditional on the relationship.', 'A gift is a gift; if you wanted a loan, you should have papered it.', 'love_romance', 'evergreen', 'curated'),
(e'A long-distance couple sets a rule that they will tell each other every time they go on a date with someone else. One of them stops mentioning a particular person. The other finds out months later.', e'Was the silence a breach?', 'Love · Honesty', 'Breach', 'Not a breach', 'A rule both agreed to is a rule both keep.', 'A particular silence is not a confession of betrayal.', 'love_romance', 'evergreen', 'curated'),
(e'A woman’s partner asks her to delete all photos of her exes from her phone. She refuses, calling it controlling. He says it is a minor request. They break up over it.', e'Was she right to refuse?', 'Love · Trust', 'Right', 'Wrong', 'A relationship that requires erasing your past is a relationship asking too much.', 'A small ask for peace of mind is not a price of admission.', 'love_romance', 'evergreen', 'curated'),
(e'A man tells his partner he is bisexual after five years of marriage. She thanks him for telling her. She also says it changes something for her she cannot describe. They divorce two years later.', e'Did he do the right thing?', 'Love · Truth', 'Right', 'Wrong', 'A truth he carried alone needed to be shared.', 'A truth that arrives five years late is a truth that should have arrived earlier.', 'love_romance', 'evergreen', 'curated'),
(e'A widow finds love again three years after losing her husband. Her adult children ask her to wait longer “for the family.” She does not. The new relationship is welcomed by half the family and avoided by the other.', e'Was she right to move on?', 'Love · Grief', 'Right', 'Wrong', 'A life remaining is a life to be lived.', 'A family is a witness to a life; their pace deserves respect.', 'love_romance', 'evergreen', 'curated'),
(e'A man cancels his wedding three days before the ceremony after a private conversation with the bride’s sister in which she revealed something he could not unhear. He never tells the bride what was said.', e'Was he right to stay silent?', 'Love · Secrets', 'Right', 'Wrong', 'A wedding cancelled is enough; details destroy two relationships.', 'A bride called off three days before a wedding deserves to know why.', 'love_romance', 'seasonal', 'curated'),

-- -----------------------------------------------------------------------------
-- crime (16)
-- -----------------------------------------------------------------------------
(e'A neighborhood collectively decides not to report a known thief to police after he begins returning stolen items and apologizing. Months later, he relapses on a different street.', e'Was the neighborhood wrong?', 'Crime · Restoration', 'Wrong', 'Not wrong', 'A relapse on the next street is the price of mercy on this one.', 'A man returning items is a man worth a second chance.', 'crime', 'evergreen', 'curated'),
(e'A teenager records a clip of a serious crime and posts it online before calling the police. The clip helps identify the perpetrator. The victim’s family asks the platform to take it down.', e'Was the teenager right?', 'Crime · Evidence', 'Right', 'Wrong', 'A viral clip is sometimes the only thing that catches a quiet criminal.', 'A victim does not consent to being broadcast.', 'crime', 'topical', 'curated'),
(e'A man chases down a pickpocket who took his wallet and beats him until he confesses. The wallet is returned. He is arrested for assault.', e'Was the arrest justified?', 'Crime · Vigilantism', 'Justified', 'Not justified', 'A society of citizens collecting their own justice is no longer a society.', 'A man who took your money does not get to walk because he was caught.', 'crime', 'evergreen', 'curated'),
(e'A bystander records a violent assault but does not intervene. The video helps convict the attacker. The victim sues the bystander for failing to act.', e'Was the lawsuit justified?', 'Crime · Bystanders', 'Justified', 'Not justified', 'A society is what we do, not what we record.', 'A bystander is not a hero who failed; he is a witness who survived.', 'crime', 'evergreen', 'curated'),
(e'A small business owner installs facial-recognition cameras after a string of shoplifting incidents. Customers protest. Shoplifting drops by 80%.', e'Was the install justified?', 'Crime · Surveillance', 'Justified', 'Not justified', 'A business that does not survive will not serve any customer.', 'A shop that scans every face has stopped being a shop.', 'crime', 'topical', 'curated'),
(e'A man hires private investigators after the police close his daughter’s missing-person case. He finds new evidence and forces the case to reopen. The investigators broke a few minor laws to get the evidence.', e'Was the man justified?', 'Crime · Justice', 'Justified', 'Not justified', 'A father is allowed to spend any resource on his daughter’s life.', 'Evidence collected illegally taints every other piece of the case.', 'crime', 'evergreen', 'curated'),
(e'A landlord refuses to rent to a man who served time for a non-violent offense ten years ago. The man cannot find housing. The landlord cites his investment risk.', e'Was the refusal justified?', 'Crime · Re-entry', 'Justified', 'Not justified', 'A landlord is allowed to manage his own risk.', 'A society that bars its returned citizens is the same society that arrested them.', 'crime', 'evergreen', 'curated'),
(e'A judge sentences a parent of three small children to two years in jail for a non-violent offense, citing the law. A social worker argues the family will collapse. The sentence stands.', e'Was the sentence right?', 'Crime · Family', 'Right', 'Wrong', 'A law is not weaker because of the family of its offender.', 'A sentence that destroys three children is a sentence with hidden costs.', 'crime', 'evergreen', 'curated'),
(e'A whistleblower exposes police corruption and is charged with leaking confidential documents. He is found guilty and serves time. The corruption he exposed leads to dozens of dismissals.', e'Was the conviction justified?', 'Crime · Truth', 'Justified', 'Not justified', 'A leak is a leak; the law cannot exempt people who shake the system.', 'A society that punishes its truth-tellers is a society that stops hearing the truth.', 'crime', 'topical', 'curated'),
(e'A man refuses to testify against a friend whom he saw commit a crime. He is held in contempt and jailed for two months. The case collapses without his testimony.', e'Was he right to refuse?', 'Crime · Loyalty', 'Right', 'Wrong', 'There are loyalties older than the courts.', 'A friend who commits a crime has already broken the friendship.', 'crime', 'evergreen', 'curated'),
(e'A small-town pharmacist quietly identifies a serial buyer of suspicious medication and reports him to the police. The buyer is arrested. The pharmacist later learns the buyer was being prescribed off-label by a doctor.', e'Was the pharmacist right?', 'Crime · Caution', 'Right', 'Wrong', 'A vigilant citizen is a public safety asset.', 'A pharmacist is not a police officer; he should not act like one.', 'crime', 'evergreen', 'curated'),
(e'A defense lawyer argues for the release of a client who confessed to her in private. The confession is privileged. The lawyer secures the release. The client commits a similar crime within a year.', e'Was the lawyer right to defend?', 'Crime · Privilege', 'Right', 'Wrong', 'Without privilege, no defense lawyer hears the truth from any client.', 'A privilege that releases the dangerous is a privilege with blood on it.', 'crime', 'evergreen', 'curated'),
(e'A neighborhood watch group reports a man for "looking suspicious" while taking out the trash. The police arrive aggressively. The man is unhurt but humiliated. The watch group declines to apologize.', e'Was the report defensible?', 'Crime · Bias', 'Defensible', 'Indefensible', 'A neighborhood watch is alerted to outliers; that is the system.', 'A watch group that reports neighbors by appearance is the harm it claims to prevent.', 'crime', 'evergreen', 'curated'),
(e'A teen vandalizes a war memorial during a protest. He is arrested. The memorial is repaired within a week. The teen is sentenced to two years.', e'Was the sentence proportionate?', 'Crime · Vandalism', 'Proportionate', 'Excessive', 'A society protects its memorials by punishing those who break them.', 'A two-year sentence for a teenager is a wound nobody can repair.', 'crime', 'evergreen', 'curated'),
(e'A man finds his neighbor’s door unlocked and a stranger inside. He locks the stranger in until police arrive. The stranger turns out to be the neighbor’s estranged brother, expected later that day.', e'Was the man right?', 'Crime · Caution', 'Right', 'Wrong', 'A neighbor’s instinct is the cheapest security a street has.', 'A man held until police arrive is a man assumed guilty.', 'crime', 'evergreen', 'curated'),
(e'A judge sentences a man to community service instead of jail for repeated minor offenses. The man does the service well. Two years later, he is convicted of a serious crime.', e'Was the original sentence wrong?', 'Crime · Mercy', 'Wrong', 'Not wrong', 'Lenient sentences for small crimes encourage larger ones.', 'A long-term outcome years later is not the verdict on the original decision.', 'crime', 'seasonal', 'curated'),

-- -----------------------------------------------------------------------------
-- the_future (16)
-- -----------------------------------------------------------------------------
(e'A government offers cash incentives for couples to have a third child after a long decline in birth rates. Activists call it coercive. The first cohort of incentivized births arrives a year later.', e'Was the incentive justified?', 'Future · Demography', 'Justified', 'Not justified', 'A country without children has no future to plan for.', 'A child born for a subsidy is a child born for the wrong reason.', 'the_future', 'topical', 'curated'),
(e'A research institute extends average life expectancy by twenty years with a treatment available only to the wealthiest. Demand for it outstrips public funding. The treatment remains private.', e'Was the institute wrong to launch it?', 'Future · Longevity', 'Wrong', 'Not wrong', 'A two-tier life expectancy is a two-tier civilization.', 'A new treatment starts where it can; access widens later.', 'the_future', 'evergreen', 'curated'),
(e'A school replaces a quarter of its teaching staff with adaptive software. Test scores hold steady; satisfaction drops. The school says results matter; some parents disagree.', e'Was the substitution justified?', 'Future · Education', 'Justified', 'Not justified', 'A child taught well by software is a child taught well.', 'A school without teachers has stopped being a school.', 'the_future', 'evergreen', 'curated'),
(e'A national government introduces a universal basic income at a modest level, paid for by a sharp wealth tax. Some wealthy citizens emigrate. Many families breathe for the first time in years.', e'Was the policy justified?', 'Future · Economy', 'Justified', 'Not justified', 'A floor under every family is a country worth its name.', 'A tax that drives out builders impoverishes the country it claims to help.', 'the_future', 'topical', 'curated'),
(e'A city legalizes fully autonomous taxis with no human oversight. Crashes drop by 30%. Many taxi drivers are pushed out of work without retraining programs in place.', e'Was the city right?', 'Future · Work', 'Right', 'Wrong', 'A 30% drop in crashes is a 30% drop in funerals.', 'A city that replaces workers without retraining is a city that broke a promise.', 'the_future', 'topical', 'curated'),
(e'A government bans children under 15 from social media. Parents who allow it are fined. Some parents argue it removes a useful channel for their introverted children.', e'Was the ban justified?', 'Future · Childhood', 'Justified', 'Not justified', 'A childhood lost to feeds is the design’s fault, not the family’s.', 'A parent is the right authority on a child, not the state.', 'the_future', 'topical', 'curated'),
(e'A national identity database links every citizen’s health, work, and travel records. Efficiency improves. A few cases of misuse leak. Officials promise tighter controls.', e'Was the database justified?', 'Future · State', 'Justified', 'Not justified', 'A modern state runs on coordinated data.', 'A database that knows everything about everyone is a database one decision away from misuse.', 'the_future', 'evergreen', 'curated'),
(e'A workplace introduces continuous productivity monitoring, including biometrics. High performers cite no problem. Lower performers leave. The company calls it a fair filter.', e'Was the system justified?', 'Future · Surveillance', 'Justified', 'Not justified', 'A workplace allowed to measure outcomes is a workplace doing its job.', 'A workplace that monitors heartbeats has lost what a workplace is for.', 'the_future', 'evergreen', 'curated'),
(e'A research lab proves that early genetic screening of fetuses can prevent several common conditions. Insurance begins requiring the screening. Families who refuse face higher premiums.', e'Was the requirement justified?', 'Future · Genetics', 'Justified', 'Not justified', 'A health system that prevents conditions cheaply should require what it can.', 'A health system that prices choice out of families is a coercive one.', 'the_future', 'topical', 'curated'),
(e'A small country grants legal personhood to a major river. Polluters can now be sued by the river itself, through court-appointed guardians. A foreign mining company calls the law absurd.', e'Was the law justified?', 'Future · Nature', 'Justified', 'Not justified', 'A river that can sue is a river that can survive.', 'Legal fictions invented to win lawsuits are a slope, not a stand.', 'the_future', 'evergreen', 'curated'),
(e'A government mandates that all generated media be tagged with a non-removable watermark identifying its origin. Independent artists worry about provenance ambiguity. Disinformation drops measurably.', e'Was the mandate justified?', 'Future · Truth', 'Justified', 'Not justified', 'A public sphere without provenance is a public sphere without truth.', 'A watermark mandated by the state is a watermark that follows you home.', 'the_future', 'topical', 'curated'),
(e'A city permits a single private company to operate all public transit, in exchange for a guaranteed price cap and 24-hour service. Two years later the cap holds; coverage is better; civic groups call the deal undemocratic.', e'Was the deal worth it?', 'Future · Civic', 'Worth it', 'Not worth it', 'A working bus is the test of governance; not who runs it.', 'A city contracted out is a city without a public spine.', 'the_future', 'evergreen', 'curated'),
(e'A regulator allows companies to sell genetic test results to advertisers if customers consent. A clear opt-out is provided. The opt-out is checked by a small minority. The market explodes.', e'Was the regulator wrong?', 'Future · Consent', 'Wrong', 'Not wrong', 'Consent buried under a default is consent shaped by design.', 'A market built on clear opt-outs is a market that respects choice.', 'the_future', 'evergreen', 'curated'),
(e'A national government bans cryptocurrencies entirely. Citizens lose access to overseas savings. Black markets emerge. The ban achieves its stated objectives in part.', e'Was the ban justified?', 'Future · Money', 'Justified', 'Not justified', 'A currency outside the state is a currency the state cannot tax fairly.', 'A ban that creates a black market is a ban that empowered the criminals it claimed to fight.', 'the_future', 'topical', 'curated'),
(e'A space agency proposes a permanent off-world settlement funded jointly by several countries. Critics call it a vanity project while many earthly problems remain unsolved. The agency proceeds.', e'Was the project justified?', 'Future · Frontier', 'Justified', 'Not justified', 'A species with somewhere else to live is a species that survives the next millennium.', 'A planet whose problems are unsolved should not pay for another planet first.', 'the_future', 'evergreen', 'curated'),
(e'A government legalizes brain-computer interfaces for medical use, with off-label use loosely policed. Within five years, executives in several industries adopt them. The labor advantage compounds.', e'Was the loose policing justified?', 'Future · Body', 'Justified', 'Not justified', 'Innovation requires room to be misused before it is shaped.', 'A device that compounds advantage is a device that decides the next generation.', 'the_future', 'seasonal', 'curated');

commit;
